please note that your ability to donate or not won't affect how you a…
For-0/vocabustudy pull request #232
Opened 2022-11-13 19:05 UTC by Nikhilatvocabustudy

…re treated on the site

I'm clarifying this because there's bound to be someone who expects admin powers, or better treatment based on how much money they're willing to spend on vocabustudy.

2022-11-13 19:06 UTC, grimsteel commented
On this note,
please note that commit messages should be 70 characters or less

2022-11-13 19:07 UTC, grimsteel requested changes

2022-11-13 19:07 UTC, grimsteel commented on src/index.pug
> +                p please note that your ability to donate or not won't affect how you are treated on the site
Capitalize this pls

2022-11-13 19:38 UTC, IMGROOT2 commented on src/index.pug
> +                p please note that your ability to donate or not won't affect how you are treated on the site
i submitted a different pull req which has proper grammar, and a discord integration. it also has the vocabustudy email on it. please refer to that- I think that it removes the need for this PR.

2022-11-14 00:19 UTC, grimsteel approved these changes

2022-11-14 00:19 UTC, merged