Includes page for youtube channel
For-0/vocabustudy pull request #252
Opened 2022-11-30 23:41 UTC by Nikhilatvocabustudy

Includes page for youtube channel

2022-12-01 01:14 UTC, IMGROOT2 commented
https://www.youtube.com/@vocabustudyandforzero is an old handle, the new one is https://www.youtube.com/@forzero , so consider changing the link.

2022-12-01 01:39 UTC, grimsteel requested changes

2022-12-01 01:39 UTC, grimsteel commented on src/index.pug
> -                h1 YouTube:
Please use correct page formatting
1. pages should be direct children of `main`
2. Hashes should be all lowercase

2022-12-01 01:39 UTC, grimsteel commented on src/index.pug
> -                p That's right, we have a YouTube channel!
This and the line below it should be indented as direct children of the page
Also, use `p` not `P` (both work but `p` conforms to style)

2022-12-01 03:44 UTC, Nikhilatvocabustudy commented on src/index.pug
> -                h1 YouTube:
I used                 .page#Youtube(data-nosnippet), is that not correct?

2022-12-01 03:50 UTC, grimsteel commented on src/index.pug
> -                h1 YouTube:
1. It has to be a direct child of main
2. Use youtube instead of Youtube

2022-12-01 03:51 UTC, grimsteel requested changes

2022-12-01 03:51 UTC, grimsteel commented on src/index.pug
> +                p That's right, we have a YouTube channel!
This have to be children of the page, not siblings

2022-12-01 03:52 UTC, grimsteel commented on src/index.pug
> +                p You can find our channel #[a(href="https://www.youtube.com/@vocabustudyandforzero") here].
Also, change this to @forzero as @IMGROOT2 said

2022-12-01 03:55 UTC, grimsteel commented
> Visit the preview URL for this PR (updated for commit [8d63dce](https://github.com/For-0/vocabustudy/commit/8d63dcebe08062213d5df7f3973e3ec3be052708)):

You can also use the preview url to see what your changes did

2022-12-01 23:58 UTC, Nikhilatvocabustudy commented on src/index.pug
> +                p That's right, we have a YouTube channel!
ah

2022-12-01 23:59 UTC, Nikhilatvocabustudy commented on src/index.pug
> +                p You can find our channel #[a(href="https://www.youtube.com/@vocabustudyandforzero") here].
the link works either ways,

2022-12-02 01:08 UTC, grimsteel requested changes
Add the correct page title to index.js

https://github.com/For-0/vocabustudy/blob/8309549225ec2cd1553d237354e8b68794b2e903/src/js/index.js#L44-L51

2022-12-02 01:08 UTC, grimsteel commented on src/index.pug
> +                h1 Youtube
The paragraph elements should be siblings, not children of the heading

2022-12-02 01:09 UTC, grimsteel commented on src/index.pug
> +                h1 Youtube
Also remember to link the youtube page somewhere

2022-12-03 03:04 UTC, grimsteel commented on src/index.pug
> +                 p If you want to check us out, do so #[a(href="https://www.youtube.com/@forzero") here].
```suggestion
                h1 Youtube
                p.mdc-typography--headline5 Check out our youtube channel
                p If you want to check us out, do so #[a(href="https://www.youtube.com/@forzero") here].
```

2022-12-04 23:38 UTC, grimsteel requested changes

2022-12-04 23:38 UTC, grimsteel commented on src/index.pug
> +                /#youtube
The footer is in layout/footer.pug

2022-12-05 03:19 UTC, grimsteel commented on src/index.pug
> +                /#youtube
```suggestion
```

2022-12-05 03:22 UTC, grimsteel commented on src/index.pug
> +                /#youtube
You need to add it here:
https://github.com/For-0/vocabustudy/blob/13be3abaa7f79ad4cd2007b7e85a1dd6b3349065/src/includes/footer.pug#L22-L44

Tips:
- do NOT add `target="_blank"` as this will open it in a new tab
- Find a good icon for it at https://fonts.google.com/icons (click the icon to find out what you have to type)
- Add 2 links, one that has the text "Youtube" in the top section, and another one with the icon that you found in the bottom section

2022-12-07 03:55 UTC, grimsteel requested changes

2022-12-07 03:55 UTC, grimsteel commented on src/includes/footer.pug
> +      a.a(href="/#youtube") Youtube
Add something like `|  | ` (with the trailing space) after this line so that it looks better

Then also copy the entire Privacy Policy button (all 3 lines) below in the other section and update it for the youtube stuff

2022-12-07 03:56 UTC, grimsteel commented on src/js/index.js
> +    "#youtube": "Youtube"
```suggestion
```

2022-12-13 00:25 UTC, grimsteel approved these changes

2022-12-13 00:25 UTC, merged