added titles of pages
For-0/vocabustudy pull request #255
Opened 2022-12-03 20:40 UTC by Nikhilatvocabustudy

2022-12-03 20:47 UTC, grimsteel requested changes

2022-12-03 20:47 UTC, grimsteel commented on src/js/index.js
> +    "Youtube": "Youtube"
I feel like there's something wrong with every line here
1. Privacy policy is it's own separate page so it shouldn't be here
2. Feedback is not a page
3. Nightly build is not a page (where are you getting these things from??)
4. Leaderboard is not a page (I literally removed it > 1 month ago!)
5. The other ones should be exactly like the hash in index.pug

2022-12-03 20:48 UTC, grimsteel commented on src/js/index.js
> +    "Youtube": "Youtube"
Also, that's not even valid JavaScript

2022-12-03 21:05 UTC, Nikhilatvocabustudy commented on src/js/index.js
> +    "Youtube": "Youtube"
sorry I did this quite rushed, so I didn't really stop to look at it

2022-12-03 21:41 UTC, grimsteel requested changes

2022-12-03 21:41 UTC, grimsteel commented on src/js/index.js
> +    "#Youtube": "Youtube"
Looks good, just make the hashes lowercase and make sure there are commas after every element that is not the last one
```suggestion
    "#discord":"Discord",
    "#donate": "Donate",
    "#youtube": "Youtube"
```

2022-12-03 21:47 UTC, grimsteel requested changes

2022-12-03 21:47 UTC, grimsteel commented on src/js/index.js
> +    "#youtube": "Youtube"
Oops - I didn't catch this:
You have to add the credits page too
```suggestion
    "#youtube": "Youtube",
    "#credits": "Credits"
```

2022-12-04 03:07 UTC, PrakmO commented on src/js/index.js
> +    "Youtube": "Youtube"
Youtube is not a page

> I feel like there's something wrong with every line here
> 
> 1. Privacy policy is it's own separate page so it shouldn't be here
> 2. Feedback is not a page
> 3. Nightly build is not a page (where are you getting these things from??)
> 4. Leaderboard is not a page (I literally removed it > 1 month ago!)
> 5. The other ones should be exactly like the hash in index.pug

2022-12-04 03:08 UTC, PrakmO commented on src/js/index.js
> +    "#Youtube": "Youtube"
But YouTube is not a page

2022-12-04 03:08 UTC, PrakmO commented on src/js/index.js
> +    "#youtube": "Youtube"
But YouTube isn't a page.... it's on Discord

2022-12-04 03:09 UTC, PrakmO commented
ok nvm to all my comments about Youtube not being a page I saw PR #255

2022-12-04 03:10 UTC, grimsteel approved these changes

2022-12-04 03:10 UTC, merged