Revamp Credits Page with Social Links
For-0/vocabustudy pull request #259
Opened 2022-12-07 23:59 UTC by IMGROOT2

It's a big change, so I made a PR.

2022-12-08 00:32 UTC, grimsteel requested changes

2022-12-08 00:32 UTC, grimsteel commented on src/index.pug
> +    link(rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css")
```suggestion
```

2022-12-08 00:32 UTC, grimsteel commented on src/index.pug
> +                        button(style="margin-right: 0.3rem" onclick="location.href='https://discordapp.com/users/698961308506390568';").button.is-small.is-discord.nohuechange #[a(href="https://discor
Download the svgs into one file and use the svg hashtag stuff idk instead of Font Awesome

2022-12-08 00:32 UTC, grimsteel commented on src/js/index.js
> +});
```suggestion
// put this in the lower one
pages.modals.credits.forEach(modal => modal.onclose = () => {});
initBulmaModals([pages.modals.reauthenticatePassword, pages.modals.changePassword, pages.modals.filterCollection, pages.modals.changeHue, pages.modals.changeName, ...pages.credits.modals /* put this in credits*/]);
```

2022-12-08 02:42 UTC, IMGROOT2 commented on src/js/index.js
> +});
i put `pages.modals.credits.forEach(modal => modal.onclose = () => {});` into the lowest one, got it. wdym by "put this in credits"?

2022-12-08 03:21 UTC, IMGROOT2 commented on src/index.pug
> +                        button(style="margin-right: 0.3rem" onclick="location.href='https://discordapp.com/users/698961308506390568';").button.is-small.is-discord.nohuechange #[a(href="https://discor
they're icons, so they can't be downloaded from the site. And they can't be found in the actual package so idk

2022-12-08 03:21 UTC, IMGROOT2 commented on src/index.pug
> +                        button(style="margin-right: 0.3rem" onclick="location.href='https://discordapp.com/users/698961308506390568';").button.is-small.is-discord.nohuechange #[a(href="https://discor
Also does the bundle size increase that much?

2022-12-08 03:31 UTC, grimsteel commented on src/js/index.js
> +});
Put the modals key as an array of the `Modal` objects on the credits page in the pages.credits object

2022-12-08 06:24 UTC, IMGROOT2 commented on src/index.pug
> +    link(rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css")
Not removing font awesome as previously written

2022-12-08 06:38 UTC, grimsteel commented on src/js/index.js
> +    document.querySelector(".contrib1").addEventListener("click", () => pages.modals.contrib1.open());
This is fine but wouldn't a for loop be better?

2022-12-08 06:40 UTC, grimsteel commented on src/index.pug
> +                        button(style="margin-right: 0.3rem" onclick="location.href='https://github.com/IMGROOT2';").button.is-small.is-github.nohuechange #[a(href="https://github.com/IMGROOT2" style=
just make the `button` an `a` to eliminate the onclick and inner element stuff

2022-12-08 07:00 UTC, IMGROOT2 commented on src/js/index.js
> +    document.querySelector(".contrib1").addEventListener("click", () => pages.modals.contrib1.open());
feel free to implement it if you'd like, i kinda want this to get merged before we continue making bulma edits, otherwise the  merge conflicts might result in a loss of code

2022-12-09 22:08 UTC, grimsteel approved these changes

2022-12-09 22:26 UTC, merged