Forms
For-0/vocabustudy pull request #279
Opened 2023-02-05 07:01 UTC by IMGROOT2

Forms Functionality.

**FIRESTORE RULES HAVE NOT BEEN DEPLOYED YET!**

2023-02-05 07:11 UTC, grimsteel requested changes

2023-02-05 07:11 UTC, grimsteel commented on src/js/forms.js
> +const toOther = document.getElementById("to-other");
collapse all of that into a forms object
kind of like this:
```js
const forms = {
  feedback: {...},
  bugs: {...},
  ...
};
```

2023-02-05 07:11 UTC, grimsteel commented on src/js/forms.js
> +        });
along with the idea of a `forms` object with subobjects for each form, you could do something like this to reduce repetition:
```js
{
  feedback: {
    btn: ...,
    form: reference to native form element,
    function: sendFeedback
  }
}

Object.values(forms).forEach(form => form.form.addEventListener("submit", ...));

2023-02-05 07:11 UTC, grimsteel commented on src/js/forms.js
> +        });
add a single submit event handler on the `main` element

for the "to" buttons, put them in an array and `forEach` it

2023-02-05 07:11 UTC, grimsteel commented on src/js/forms.js
> +        feedbackBtn.innerHTML = "Submitted!";
```suggestion
        feedbackBtn.innerText = "Submitted!";
```

2023-02-05 07:11 UTC, grimsteel commented on src/forms.pug
> +                                    | Submit Other Request
some of these could be collapsed onto one line
```suggestion
                                button#btn-other.button.is-primary Submit Other Request
```

2023-02-05 07:14 UTC, grimsteel commented on src/forms.pug
> +                            | We generally discourage use of this form, in favor of #[a(href="https://github.com/For-0/vocabustudy/issues") #[img(src="icons/brands/github.svg" style="height: 1em; ver
```suggestion
                            | We generally discourage use of this form, in favor of #[a.icon-text(href="https://github.com/For-0/vocabustudy/issues") #[span.icon.mr-2 #[img(src="icons/brands/github.svg")]] GitHub Issues.] If you can, please use that instead.
```

2023-02-05 18:30 UTC, grimsteel requested changes

2023-02-05 18:30 UTC, grimsteel commented on src/forms.pug
> +                                input#email-feedback.input(type="email" name="email" placeholder="Your Email" required="required")
This isn't XHTML :wink:
```suggestion
                                input#email-feedback.input(type="email" name="email" placeholder="Your Email" required)
```

2023-02-05 18:30 UTC, grimsteel commented on src/js/forms.js
> +        feedbackForm.addEventListener('submit',  async (e) => {
could you please modularize this? the repetition just decreases readability

2023-02-05 18:36 UTC, grimsteel requested changes
Everything looks great, thanks! However the heroes are too big (esp. on chromebooks) so could you remove `.is-medium` from them? The content of the page under the heroes really matters more

Also add this:
```css
left: -1rem;
position: relative;
width: calc(100% + 2rem);
```
to all the heroes (maybe in the `extrahead` block?) to make them full width

2023-02-05 18:37 UTC, grimsteel approved these changes

2023-02-05 18:40 UTC, grimsteel commented
contrary to what github says, I did _not_ approve the changes

this is why you always check where you are typing before pressing "enter"

2023-02-05 19:55 UTC, IMGROOT2 commented on src/js/forms.js
> +        feedbackForm.addEventListener('submit',  async (e) => {
this is probably old because I did that already

2023-02-06 02:21 UTC, grimsteel commented on firestore.rules
> +    }
We should probably make this more secure (put the function at the top with the other functions):
```suggestion
    function validateFormResponse(additionalKeys) {
      let requiredFields = ["name", "email", "text", "uid"];
      return limitResourceKeys(requiredFields.concat(additionalKeys), []);
    }
    match /form_data/types/{form_type}/{submission_id} {
      allow get: if resource == null || isCreator();
      allow list, delete: if isCreator();
      allow create: if auth() && form_type in ["feedback", "bug", "takedown", "other"] && request.resource.data.keys().hasAll(["name", "email", "text", "uid])
        (form_type == "feedback" && validateFormResponse(["rating"])) ||
        (form_type == "feedback" && validateFormResponse(["url"])) ||
        (form_type == "feedback" && validateFormResponse(["url"])) ||
        (form_type == "feedback" && validateFormResponse([])));
    }
```

2023-02-06 05:47 UTC, merged